/**
 * Encodes the Inter woff fonts as base64 strings into api/_fonts.ts so the
 * OG image function can render text without depending on the filesystem
 * or static asset URLs (which 401 on auth-protected preview deploys).
 *
 * Run when the bundled fonts change: npm run gen:fonts
 */

import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const FONT_SRC = join(import.meta.dirname, 'fonts');
const OUT = join(import.meta.dirname, '..', 'api', '_fonts.ts');
// resvg-js@2.6.2 (native binding) reliably renders TTF/OTF.
const FILES = ['inter-400.ttf', 'inter-700.ttf', 'inter-900.ttf'];

const lines = [
  '// Auto-generated by scripts/gen-fonts.ts. Do not edit by hand.',
  '// Fonts inlined so the OG image renders text in all environments,',
  '// including preview deploys behind Vercel auth.',
  '',
];
for (const f of FILES) {
  const b64 = readFileSync(join(FONT_SRC, f)).toString('base64');
  const name = f.replace(/[-.]/g, '_').replace(/_(ttf|woff2?)$/, '');
  lines.push(`export const ${name} = '${b64}';`);
}
writeFileSync(OUT, lines.join('\n') + '\n');
console.log(`Wrote ${OUT}`);
